### ISSUE TITLE
PP rebalance

### ISSUE THREAD

**Issue by ghost** [Francesco149/ojsama#12]
Will the ojsama library be updated to accommodate for the PP rebalance coming soon? 

Thanks in advance

**Comment by Francesco149** [comment]
yea i already have the changes written for the C implementation and porting them wont be too hard

**Comment by ghost** [comment]
Thanks for the swift reply! Looking forward to an update :) Is there an approximate ETA you could give once the changes have been made public?

**Comment by Francesco149** [comment]
within 1 day after the leaderboards have recalculated and i can produce an updated test suite, but i will have code ready in pull requests before that for people who want to use it early

**Comment by Francesco149** [comment]
you can check out the latest pp changes here, will be merged when recalc happens 
https://github.com/Francesco149/ojsama/pull/10

**Comment by Francesco149** [comment]
released
