### ISSUE TITLE
Wrong PP calculation with DT

### ISSUE THREAD

**Issue by autriz** [Francesco149/ojsama#21]
Hi, when i trying to get a pp from a recent map
```
return pp = oj.ppv2({

            aim_stars: Number(score.beatmap.difficulty.aim),
            speed_stars: Number(score.beatmap.difficulty.speed),
            base_ar: Number(score.beatmap.difficulty.approach),
            base_od: Number(score.beatmap.difficulty.overall),
            n300: Number(score.counts["300"]),
            n100: Number(score.counts["100"]),
            n50: Number(score.counts["50"]),
            nmiss: Number(score.counts.miss),
            mods: modlist,
            combo: Number(score.maxCombo),
            ncircles: Number(score.beatmap.objects.normal),
            nsliders: Number(score.beatmap.objects.slider),
            nobjects: (score.beatmap.objects.normal - 0) + (score.beatmap.objects.slider - 0) + (score.beatmap.objects.spinner - 0),
            max_combo: Number(score.beatmap.maxCombo),

        })

```
it returns a pp slightly higher than a pp calc with nomod

For example, [map](https://osu.ppy.sh/beatmapsets/1183876#osu/2475392) with nomod shows
```
std_ppv2 {
  aim: 12.629888687462195,
  speed: 8.936980742489745,
  acc: 0.5142704999811265,
  computed_accuracy: std_accuracy { nmiss: 1, n300: 227, n100: 19, n50: 0 },
  total: 23.075477232601955
}
```
and with DT
```
std_ppv2 {
  aim: 12.806240309529043,
  speed: 9.134035336618599,
  acc: 1.3379846868929575,
  computed_accuracy: std_accuracy { nmiss: 1, n300: 227, n100: 19, n50: 0 },
  total: 24.138883579320098
}
```

If this issue on my side, or params are wrong, please help me fix it

**Comment by Francesco149** [comment]
if you're gonna use aim/speed stars from other sources then you should adjust them for DT. not sure if you're pulling those from the osu API, but if it's from the osu API it should provide multiple star values for different mods.

**Comment by autriz** [comment]
I'm using node-osu for that and there's star values only for nomod, unfortunately

**Comment by Francesco149** [comment]
then you shouldn't provide the star values and let ojsama do the diff calc

**Comment by autriz** [comment]
don't understand how correctly parse a beatmap for diff calc in my case

**Comment by Francesco149** [comment]
you have to obtain the .osu file first,  then just open the .osu file and pass it to the parser like in the example https://github.com/Francesco149/ojsama/blob/master/example.js#L32

instead of stdin you'd pass something like `fs.createReadStream('file.osu')` to readline

**Comment by autriz** [comment]
unfortunately, i can't do ```fs.createReadStream('file.osu')``` in my code, but i found another way to obtain aim and speed values
thanks for help
