### ISSUE TITLE
ppv2's prototype toString function sometimes returns Infinity

### ISSUE THREAD

**Issue by knht** [Francesco149/ojsama#8]
As the title states, the toString() prototype function sometimes returns Infinity for custom PP calculations.

I feed ppv2 as follows:

```js
const bmStars = new ojs.diff().calc({ map: beatmapParser.map, mods: parseInt(userRecents[0].enabled_mods) });
const achievedPP = ojs.ppv2({
    stars: bmStars,
    combo: parseInt(userRecents[0].maxcombo),
    n300: parseInt(userRecents[0].count300),
    n100: parseInt(userRecents[0].count100),
    n50: parseInt(userRecents[0].count50),
    nmiss: parseInt(userRecents[0].countmiss)
});
```

And format the prototype as follows for just the PP:

```js
const formattedAchievedPP = achievedPP.toString().split(" ", 1)[0];
```

My problem occurs completely random and I'd say in around 1/10 cases.

Is there any possible solution to this or is my code wrong at some point? Thanks for your help, highly appreciated!

**Comment by knht** [comment]
Looking closer at it, the difficulty calculation seems to fail:

```
0.00 stars (0.00 aim, 0.00 speed)
```

Because the beatmap parser returns 0 sliders, circles and spinners:

```
AR9.3 OD8.7 CS4.3 HP5.5
0 circles, 0 sliders, 0 spinners
0 max combo
```

The beatmap data fed to the beatmap parser: https://kirameki.one/staticdata/beatmap.osu.txt

Any idea why this is happening? Thanks in advance

**Comment by Francesco149** [comment]
the beatmap is actually empty. check the file you linked me, it has no [HitObjects] section or whatever it's called

the file looks like it's almost exactly 1mb so it's likely that it's one of those maps that suffers from the bug that truncates .osu files to 1mb when you download them from the site https://github.com/ppy/osu-api/issues/131

i guess i should avoid making it return infinity pp though, so i'll keep the issue open

**Comment by knht** [comment]
Thank you very much for your swift response. Another issue I'm currently facing is that around 2/10 times ojsama crashes Nodejs with an uncaught error:

```
TypeError: Cannot read property 'trim' of undefined
```

Full stack trace:

```
at parser._setpos (/home/kirameki/dev/kiramekibot/kiramekidiscord/node_modules/ojsama/ojsama.js:625:24)
at parser._property (/home/kirameki/dev/kiramekibot/kiramekidiscord/node_modules/ojsama/ojsama.js:641:17)
at parser._difficulty (/home/kirameki/dev/kiramekibot/kiramekidiscord/node_modules/ojsama/ojsama.js:687:18)
at parser.feed_line (/home/kirameki/dev/kiramekibot/kiramekidiscord/node_modules/ojsama/ojsama.js:584:29)
at parser.feed (/home/kirameki/dev/kiramekibot/kiramekidiscord/node_modules/ojsama/ojsama.js:606:14)
at fs.readFile (/home/kirameki/dev/kiramekibot/kiramekidiscord/src/commands/OsuRecent.js:57:77)
at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

Line 57 of the OsuRecent.js file:

```js
var beatmapParser = new ojs.parser().feed(beatmapData);
```

I download the .osu file and save it temporarily, then read it with fs and feed that to the parser, which seems to fail sometimes. Is there anything I missed or could you propose a better solution to feeding the parser without a command line in nodejs? Thanks :)

**Comment by Francesco149** [comment]
can you send me a sample .osu file that does this? it could be that there's some unexpected stuff in the metadata section of the beatmap that I'm not handling

**Comment by knht** [comment]
Sure. I stumbled upon something even weirder now. This map is sometimes throwing the trim is undefined error and sometimes returns Infinity / NaN completely at random, without changing the .osu file or any code. https://pastebin.com/raw/C2L9Lb7j I'm completely lost with that and really can't tell what's going on at this point

**Comment by Francesco149** [comment]
hmm I tried to run example.js against that .osu file with different mods multiple times without getting any error, but that uses feed_line instead of feed and reads the file line by line using the readline interface.

I tried changing it to use readFile and read the entire file from disk and it still doesn't crash

https://gist.github.com/eb4e1e12d0d6a7ae67ff0be84dc4e1ac

```node example.js ~/Downloads/test.osu +HDDT 95%```

I think you should try logging your beatmapData before you feed it to the parser, then wait for it to crash and see what the beatmap data was. or try using the readline interface and read the file line by line like example.js does, but I doubt that's the issue since both work fine for me.

**Comment by knht** [comment]
Thank you very much for your detailed example. I think I fixed the problem by reading the .osu file synchronously. I don't know why, but reading the file with fs asynchronously, the data variable of the callback (sometimes) ended up incomplete.
